# Public OCI Helm registry for Microsoft charts; no credentials.
apiVersion: v1
kind: Secret
metadata:
  name: repo-mcr-application-lb
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: mcr-application-lb
  type: helm
  url: mcr.microsoft.com/application-lb/charts
  enableOCI: "true"
